name: Deploy ASP.NET Core to MonsterASP

on:
push:
branches:
- master

jobs:
build-and-deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: '8.0.x'

  - name: Restore dependencies
    run: dotnet restore

  - name: Publish project
    run: dotnet publish GymManagementSystem.WebUI/GymManagementSystem.WebUI.csproj -c Release -o publish

  - name: Deploy to FTP
    uses: SamKirkland/FTP-Deploy-Action@v3.1.1
    with:
      ftp-server: ${{ secrets.FTP_SERVER }}
      ftp-username: ${{ se
```
